# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' z-Normalize a time series
#'
#' @param x A time series.
#' @param threshold A z-normalization threshold.
#' @useDynLib jmotif
#' @export
#' @examples
#' x = seq(0, pi*4, 0.02)
#' y = sin(x) * 5 + rnorm(length(x))
#' plot(x, y, type="l", col="blue")
#' lines(x, znorm(y, 0.01), type="l", col="red")
znorm <- function(x, threshold = 0.01) {
    .Call('jmotif_znorm', PACKAGE = 'jmotif', x, threshold)
}

#' Reshape matrix
#'
#' @param a A matrix to reshape.
#' @param n new row size.
#' @param m new column size.
#' @useDynLib jmotif
#' @export
reshape_cpp <- function(a, n, m) {
    .Call('jmotif_reshape_cpp', PACKAGE = 'jmotif', a, n, m)
}

#' Computes column means
#'
#' @param a A matrix to use.
#' @useDynLib jmotif
#' @export
col_means_cpp <- function(a) {
    .Call('jmotif_col_means_cpp', PACKAGE = 'jmotif', a)
}

#' Compute PAA
#'
#' @param ts A timeseries to convert into PAA.
#' @param paa_num the desired PAA size.
#' @useDynLib jmotif
#' @export
#' @examples
#' #' x = c(-1, -2, -1, 0, 2, 1, 1, 0)
#' plot(x,type="l",main="8-points time series and it PAA transform into three points")
#' points(x,pch=16,lwd=5)
#' #segments
#' abline(v=c(1,1+7/3,1+7/3*2,8),lty=3,lwd=2)
paa <- function(ts, paa_num) {
    .Call('jmotif_paa', PACKAGE = 'jmotif', ts, paa_num)
}

#' Get a letter by index
#'
#' @param idx The index.
#' @useDynLib jmotif
#' @export
idx2letter_cpp <- function(idx) {
    .Call('jmotif_idx2letter_cpp', PACKAGE = 'jmotif', idx)
}

#' Get an index for a letter
#'
#' @param letter The letter.
#' @useDynLib jmotif
#' @export
letter2idx_cpp <- function(letter) {
    .Call('jmotif_letter2idx_cpp', PACKAGE = 'jmotif', letter)
}

#' Get an index sequence by string
#'
#' @param str The char array.
#' @useDynLib jmotif
#' @export
letters2idx_cpp <- function(str) {
    .Call('jmotif_letters2idx_cpp', PACKAGE = 'jmotif', str)
}

#' Translates an alphabet size into the array of corresponding
#' SAX cut-lines assuming the Normal distribution
#'
#' @param a_size the alphabet size, a value between 2 and 20 (inclusive).
#' @useDynLib jmotif
#' @export
alphabet2cuts_cpp <- function(a_size) {
    .Call('jmotif_alphabet2cuts_cpp', PACKAGE = 'jmotif', a_size)
}

#' Transforms a time series into a char array
#'
#' @param ts the timeseries
#' @param a_size the alphabet size
#' @useDynLib jmotif
#' @export
ts2chars_cpp <- function(ts, a_size) {
    .Call('jmotif_ts2chars_cpp', PACKAGE = 'jmotif', ts, a_size)
}

#' Transforms a time series into a char array
#'
#' @param ts the timeseries
#' @param a_size the alphabet size
#' @useDynLib jmotif
#' @export
ts2string_cpp <- function(ts, a_size) {
    .Call('jmotif_ts2string_cpp', PACKAGE = 'jmotif', ts, a_size)
}

#' Extracting subseries
#'
#' @param x the timeseries (0-based)
#' @param start the interval start
#' @param end the interval end
#' @useDynLib jmotif
#' @export
subseries <- function(x, start, end) {
    .Call('jmotif_subseries', PACKAGE = 'jmotif', x, start, end)
}

#' Comparing strings
#'
#' @param a the string a
#' @param b the string b
#' @useDynLib jmotif
#' @export
is_equal_str <- function(a, b) {
    .Call('jmotif_is_equal_str', PACKAGE = 'jmotif', a, b)
}

#' SAXifying a timeseries
#'
#' @param ts the timeseries
#' @param w_size the sliding window size
#' @param paa_size the PAA size
#' @param a_size the alphabet size
#' @param nr_strategy the NR strategy
#' @param n_threshold the normalization threshold
#'
#' @useDynLib jmotif
#' @export
sax_via_window <- function(ts, w_size, paa_size, a_size, nr_strategy, n_threshold) {
    .Call('jmotif_sax_via_window', PACKAGE = 'jmotif', ts, w_size, paa_size, a_size, nr_strategy, n_threshold)
}

#' SAXifying a timeseries
#'
#' @param ts the timeseries
#' @param paa_size the PAA size
#' @param a_size the alphabet size
#' @param n_threshold the normalization threshold
#'
#' @useDynLib jmotif
#' @export
sax_by_chunking <- function(ts, paa_size, a_size, n_threshold) {
    .Call('jmotif_sax_by_chunking', PACKAGE = 'jmotif', ts, paa_size, a_size, n_threshold)
}

#' SAXifying a timeseries
#'
#' @param ts the timeseries
#' @param w_size the sliding window size
#' @param paa_size the PAA size
#' @param a_size the alphabet size
#' @param nr_strategy the NR strategy
#' @param n_threshold the normalization threshold
#'
#' @useDynLib jmotif
#' @export
series_to_wordbag <- function(ts, w_size, paa_size, a_size, nr_strategy, n_threshold) {
    .Call('jmotif_series_to_wordbag', PACKAGE = 'jmotif', ts, w_size, paa_size, a_size, nr_strategy, n_threshold)
}

