name: lint

on:
  push:
    branches: [main, master, development]
    paths:
      - '**.R'
      - '**.Rmd'
      - '**.qmd'
      - DESCRIPTION
      - NAMESPACE
      - .lintr
  pull_request:
    branches: [main, master, development]
    paths:
      - '**.R'
      - '**.Rmd'
      - '**.qmd'
      - DESCRIPTION
      - NAMESPACE
      - .lintr

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install lintr (and local deps if needed)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: true
          extra-packages: |
            any::lintr
            local::.

      - name: Run lintr
        shell: Rscript {0}
        run: |
          cat("lintr version: ", as.character(utils::packageVersion("lintr")), "\n")
          lintr::lint_package()

